/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkGalleryRouteImport } from './routes/work.gallery'
import { Route as WorkCvesRouteImport } from './routes/work.cves'
import { Route as WorkCaseStudiesRouteImport } from './routes/work.case-studies'
import { Route as WorkBlogRouteImport } from './routes/work.blog'
import { Route as WorkProjectRouteImport } from './routes/work.$project'
import { Route as ExperienceTestimonialsRouteImport } from './routes/experience.testimonials'
import { Route as ExperienceServicesRouteImport } from './routes/experience.services'
import { Route as ExperienceCertificationsRouteImport } from './routes/experience.certifications'
import { Route as ExperienceAwardsRouteImport } from './routes/experience.awards'
import { Route as AboutUsesRouteImport } from './routes/about.uses'
import { Route as AboutSkillsRouteImport } from './routes/about.skills'
import { Route as AboutNowRouteImport } from './routes/about.now'
import { Route as AboutEducationRouteImport } from './routes/about.education'
import { Route as WorkCvesIndexRouteImport } from './routes/work.cves.index'
import { Route as WorkCvesSlugRouteImport } from './routes/work.cves.$slug'
import { Route as WorkBlogSlugRouteImport } from './routes/work.blog.$slug'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkGalleryRoute = WorkGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => WorkRoute,
} as any)
const WorkCvesRoute = WorkCvesRouteImport.update({
  id: '/cves',
  path: '/cves',
  getParentRoute: () => WorkRoute,
} as any)
const WorkCaseStudiesRoute = WorkCaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => WorkRoute,
} as any)
const WorkBlogRoute = WorkBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => WorkRoute,
} as any)
const WorkProjectRoute = WorkProjectRouteImport.update({
  id: '/$project',
  path: '/$project',
  getParentRoute: () => WorkRoute,
} as any)
const ExperienceTestimonialsRoute = ExperienceTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => ExperienceRoute,
} as any)
const ExperienceServicesRoute = ExperienceServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => ExperienceRoute,
} as any)
const ExperienceCertificationsRoute =
  ExperienceCertificationsRouteImport.update({
    id: '/certifications',
    path: '/certifications',
    getParentRoute: () => ExperienceRoute,
  } as any)
const ExperienceAwardsRoute = ExperienceAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => ExperienceRoute,
} as any)
const AboutUsesRoute = AboutUsesRouteImport.update({
  id: '/uses',
  path: '/uses',
  getParentRoute: () => AboutRoute,
} as any)
const AboutSkillsRoute = AboutSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AboutRoute,
} as any)
const AboutNowRoute = AboutNowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => AboutRoute,
} as any)
const AboutEducationRoute = AboutEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => AboutRoute,
} as any)
const WorkCvesIndexRoute = WorkCvesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkCvesRoute,
} as any)
const WorkCvesSlugRoute = WorkCvesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkCvesRoute,
} as any)
const WorkBlogSlugRoute = WorkBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRouteWithChildren
  '/work': typeof WorkRouteWithChildren
  '/about/education': typeof AboutEducationRoute
  '/about/now': typeof AboutNowRoute
  '/about/skills': typeof AboutSkillsRoute
  '/about/uses': typeof AboutUsesRoute
  '/experience/awards': typeof ExperienceAwardsRoute
  '/experience/certifications': typeof ExperienceCertificationsRoute
  '/experience/services': typeof ExperienceServicesRoute
  '/experience/testimonials': typeof ExperienceTestimonialsRoute
  '/work/$project': typeof WorkProjectRoute
  '/work/blog': typeof WorkBlogRouteWithChildren
  '/work/case-studies': typeof WorkCaseStudiesRoute
  '/work/cves': typeof WorkCvesRouteWithChildren
  '/work/gallery': typeof WorkGalleryRoute
  '/work/blog/$slug': typeof WorkBlogSlugRoute
  '/work/cves/$slug': typeof WorkCvesSlugRoute
  '/work/cves/': typeof WorkCvesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRouteWithChildren
  '/work': typeof WorkRouteWithChildren
  '/about/education': typeof AboutEducationRoute
  '/about/now': typeof AboutNowRoute
  '/about/skills': typeof AboutSkillsRoute
  '/about/uses': typeof AboutUsesRoute
  '/experience/awards': typeof ExperienceAwardsRoute
  '/experience/certifications': typeof ExperienceCertificationsRoute
  '/experience/services': typeof ExperienceServicesRoute
  '/experience/testimonials': typeof ExperienceTestimonialsRoute
  '/work/$project': typeof WorkProjectRoute
  '/work/blog': typeof WorkBlogRouteWithChildren
  '/work/case-studies': typeof WorkCaseStudiesRoute
  '/work/gallery': typeof WorkGalleryRoute
  '/work/blog/$slug': typeof WorkBlogSlugRoute
  '/work/cves/$slug': typeof WorkCvesSlugRoute
  '/work/cves': typeof WorkCvesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRouteWithChildren
  '/work': typeof WorkRouteWithChildren
  '/about/education': typeof AboutEducationRoute
  '/about/now': typeof AboutNowRoute
  '/about/skills': typeof AboutSkillsRoute
  '/about/uses': typeof AboutUsesRoute
  '/experience/awards': typeof ExperienceAwardsRoute
  '/experience/certifications': typeof ExperienceCertificationsRoute
  '/experience/services': typeof ExperienceServicesRoute
  '/experience/testimonials': typeof ExperienceTestimonialsRoute
  '/work/$project': typeof WorkProjectRoute
  '/work/blog': typeof WorkBlogRouteWithChildren
  '/work/case-studies': typeof WorkCaseStudiesRoute
  '/work/cves': typeof WorkCvesRouteWithChildren
  '/work/gallery': typeof WorkGalleryRoute
  '/work/blog/$slug': typeof WorkBlogSlugRoute
  '/work/cves/$slug': typeof WorkCvesSlugRoute
  '/work/cves/': typeof WorkCvesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/experience'
    | '/work'
    | '/about/education'
    | '/about/now'
    | '/about/skills'
    | '/about/uses'
    | '/experience/awards'
    | '/experience/certifications'
    | '/experience/services'
    | '/experience/testimonials'
    | '/work/$project'
    | '/work/blog'
    | '/work/case-studies'
    | '/work/cves'
    | '/work/gallery'
    | '/work/blog/$slug'
    | '/work/cves/$slug'
    | '/work/cves/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/experience'
    | '/work'
    | '/about/education'
    | '/about/now'
    | '/about/skills'
    | '/about/uses'
    | '/experience/awards'
    | '/experience/certifications'
    | '/experience/services'
    | '/experience/testimonials'
    | '/work/$project'
    | '/work/blog'
    | '/work/case-studies'
    | '/work/gallery'
    | '/work/blog/$slug'
    | '/work/cves/$slug'
    | '/work/cves'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/experience'
    | '/work'
    | '/about/education'
    | '/about/now'
    | '/about/skills'
    | '/about/uses'
    | '/experience/awards'
    | '/experience/certifications'
    | '/experience/services'
    | '/experience/testimonials'
    | '/work/$project'
    | '/work/blog'
    | '/work/case-studies'
    | '/work/cves'
    | '/work/gallery'
    | '/work/blog/$slug'
    | '/work/cves/$slug'
    | '/work/cves/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  ContactRoute: typeof ContactRoute
  ExperienceRoute: typeof ExperienceRouteWithChildren
  WorkRoute: typeof WorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/gallery': {
      id: '/work/gallery'
      path: '/gallery'
      fullPath: '/work/gallery'
      preLoaderRoute: typeof WorkGalleryRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/cves': {
      id: '/work/cves'
      path: '/cves'
      fullPath: '/work/cves'
      preLoaderRoute: typeof WorkCvesRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/case-studies': {
      id: '/work/case-studies'
      path: '/case-studies'
      fullPath: '/work/case-studies'
      preLoaderRoute: typeof WorkCaseStudiesRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/blog': {
      id: '/work/blog'
      path: '/blog'
      fullPath: '/work/blog'
      preLoaderRoute: typeof WorkBlogRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/$project': {
      id: '/work/$project'
      path: '/$project'
      fullPath: '/work/$project'
      preLoaderRoute: typeof WorkProjectRouteImport
      parentRoute: typeof WorkRoute
    }
    '/experience/testimonials': {
      id: '/experience/testimonials'
      path: '/testimonials'
      fullPath: '/experience/testimonials'
      preLoaderRoute: typeof ExperienceTestimonialsRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/services': {
      id: '/experience/services'
      path: '/services'
      fullPath: '/experience/services'
      preLoaderRoute: typeof ExperienceServicesRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/certifications': {
      id: '/experience/certifications'
      path: '/certifications'
      fullPath: '/experience/certifications'
      preLoaderRoute: typeof ExperienceCertificationsRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/awards': {
      id: '/experience/awards'
      path: '/awards'
      fullPath: '/experience/awards'
      preLoaderRoute: typeof ExperienceAwardsRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/about/uses': {
      id: '/about/uses'
      path: '/uses'
      fullPath: '/about/uses'
      preLoaderRoute: typeof AboutUsesRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/skills': {
      id: '/about/skills'
      path: '/skills'
      fullPath: '/about/skills'
      preLoaderRoute: typeof AboutSkillsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/now': {
      id: '/about/now'
      path: '/now'
      fullPath: '/about/now'
      preLoaderRoute: typeof AboutNowRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/education': {
      id: '/about/education'
      path: '/education'
      fullPath: '/about/education'
      preLoaderRoute: typeof AboutEducationRouteImport
      parentRoute: typeof AboutRoute
    }
    '/work/cves/': {
      id: '/work/cves/'
      path: '/'
      fullPath: '/work/cves/'
      preLoaderRoute: typeof WorkCvesIndexRouteImport
      parentRoute: typeof WorkCvesRoute
    }
    '/work/cves/$slug': {
      id: '/work/cves/$slug'
      path: '/$slug'
      fullPath: '/work/cves/$slug'
      preLoaderRoute: typeof WorkCvesSlugRouteImport
      parentRoute: typeof WorkCvesRoute
    }
    '/work/blog/$slug': {
      id: '/work/blog/$slug'
      path: '/$slug'
      fullPath: '/work/blog/$slug'
      preLoaderRoute: typeof WorkBlogSlugRouteImport
      parentRoute: typeof WorkBlogRoute
    }
  }
}

interface AboutRouteChildren {
  AboutEducationRoute: typeof AboutEducationRoute
  AboutNowRoute: typeof AboutNowRoute
  AboutSkillsRoute: typeof AboutSkillsRoute
  AboutUsesRoute: typeof AboutUsesRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutEducationRoute: AboutEducationRoute,
  AboutNowRoute: AboutNowRoute,
  AboutSkillsRoute: AboutSkillsRoute,
  AboutUsesRoute: AboutUsesRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface ExperienceRouteChildren {
  ExperienceAwardsRoute: typeof ExperienceAwardsRoute
  ExperienceCertificationsRoute: typeof ExperienceCertificationsRoute
  ExperienceServicesRoute: typeof ExperienceServicesRoute
  ExperienceTestimonialsRoute: typeof ExperienceTestimonialsRoute
}

const ExperienceRouteChildren: ExperienceRouteChildren = {
  ExperienceAwardsRoute: ExperienceAwardsRoute,
  ExperienceCertificationsRoute: ExperienceCertificationsRoute,
  ExperienceServicesRoute: ExperienceServicesRoute,
  ExperienceTestimonialsRoute: ExperienceTestimonialsRoute,
}

const ExperienceRouteWithChildren = ExperienceRoute._addFileChildren(
  ExperienceRouteChildren,
)

interface WorkBlogRouteChildren {
  WorkBlogSlugRoute: typeof WorkBlogSlugRoute
}

const WorkBlogRouteChildren: WorkBlogRouteChildren = {
  WorkBlogSlugRoute: WorkBlogSlugRoute,
}

const WorkBlogRouteWithChildren = WorkBlogRoute._addFileChildren(
  WorkBlogRouteChildren,
)

interface WorkCvesRouteChildren {
  WorkCvesSlugRoute: typeof WorkCvesSlugRoute
  WorkCvesIndexRoute: typeof WorkCvesIndexRoute
}

const WorkCvesRouteChildren: WorkCvesRouteChildren = {
  WorkCvesSlugRoute: WorkCvesSlugRoute,
  WorkCvesIndexRoute: WorkCvesIndexRoute,
}

const WorkCvesRouteWithChildren = WorkCvesRoute._addFileChildren(
  WorkCvesRouteChildren,
)

interface WorkRouteChildren {
  WorkProjectRoute: typeof WorkProjectRoute
  WorkBlogRoute: typeof WorkBlogRouteWithChildren
  WorkCaseStudiesRoute: typeof WorkCaseStudiesRoute
  WorkCvesRoute: typeof WorkCvesRouteWithChildren
  WorkGalleryRoute: typeof WorkGalleryRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkProjectRoute: WorkProjectRoute,
  WorkBlogRoute: WorkBlogRouteWithChildren,
  WorkCaseStudiesRoute: WorkCaseStudiesRoute,
  WorkCvesRoute: WorkCvesRouteWithChildren,
  WorkGalleryRoute: WorkGalleryRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  ContactRoute: ContactRoute,
  ExperienceRoute: ExperienceRouteWithChildren,
  WorkRoute: WorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
